apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-cbkr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/rs-demos-fdgf-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-cbkr@sha256:ddac05f7eb47130d2f52366eaeeaec9097fe17fae656d4cbca087badb920dfdc
        name: main
        resources: {}
status: {}
